import FEATURE_NAME from "./featureName";

const featureSwitch = [
  {
    id: 1,
    identifier: FEATURE_NAME.LOGBOOKS,
    name: "Number of logbooks",
    iconName: "book",
    free: 2,
    premium: 100,
  },
  {
    id: 2,
    identifier: FEATURE_NAME.DEVICES,
    name: "Maximum devices per account",
    iconName: "person",
    free: 1,
    premium: 100,
  },
  {
    id: 3,
    identifier: FEATURE_NAME.BUDGETS,
    name: "Budgets",
    iconName: "pie-chart",
    free: 1,
    premium: 100,
  },
  {
    id: 4,
    identifier: FEATURE_NAME.LOAN,
    name: "Loan contacts",
    iconName: "cash",
    free: 5,
    premium: 100,
  },
  {
    id: 5,
    identifier: FEATURE_NAME.SECONDARY_CURRENCY,
    name: "Secondary currency",
    iconName: "logo-usd",
    free: true,
    premium: true,
  },
  {
    id: 6,
    identifier: FEATURE_NAME.EXPORT_DATA,
    name: "Export data",
    iconName: "share-outline",
    free: false,
    premium: true,
  },
  {
    id: 7,
    identifier: FEATURE_NAME.ATTACHMENT_IMAGES,
    name: `Attachment images\n(coming soon)`,
    iconName: "image",
    free: false,
    premium: true,
  },
  {
    id: 8,
    identifier: FEATURE_NAME.RECURRING_TRANSACTIONS,
    name: `Recurring transactions\n(coming soon)`,
    iconName: "repeat",
    free: false,
    premium: true,
  },
  // {
  //   id: 9,
  //   identifier: FEATURE_NAME.FEATURE_WISHLIST,
  //   name: "Feature wishlist",
  //   iconName: "bulb",
  //   free: false,
  //   premium: true,
  // },
  // {
  //   id: 10,
  //   identifier: FEATURE_NAME.GROUPS,
  //   name: "Groups and sharing logbooks",
  //   iconName: "people",
  //   free: false,
  //   premium: true,
  // },
];

export default featureSwitch;
