const SUBSCRIPTION_LIMIT = {
  LOGBOOKS: "LOGBOOKS_LIMIT",
  DEVICES: "DEVICES_LIMIT",
  SECONDARY_CURRENCY: "SECONDARY_CURRENCY",
  RECURRING_TRANSACTIONS: "RECURRING_TRANSACTIONS",
  EXPORT_DATA: "EXPORT_DATA",
  BUDGETS: "BUDGETS_LIMIT",
  GROUPS: "GROUPS_LIMIT",
  FEATURE_WISHLIST: "FEATURE_WISHLIST",
};

export default SUBSCRIPTION_LIMIT;
