const CURRENCY_CONSTANTS = {
  DEFAULT: {
    name: "United States of America",
    currencyCode: "USD",
    symbol: "$",
    isoCode: "us",
    thousandSeparator: ",",
    significantDigits: 2,
    decimalSeparator: ".",
  },
  OPTIONS: [
    {
      name: "Afghanistan",
      currencyCode: "AFN",
      symbol: "؋",
      isoCode: "af",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Albania",
      currencyCode: "ALL",
      symbol: "Lek",
      isoCode: "al",
      thousandSeparator: ".",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Algeria",
      currencyCode: "DZD",
      symbol: "د.ج",
      isoCode: "dz",
      thousandSeparator: ".",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Andorra",
      currencyCode: "EUR",
      symbol: "€",
      isoCode: "ad",
      thousandSeparator: ".",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Angola",
      currencyCode: "AOA",
      symbol: "Kz",
      isoCode: "ao",
      thousandSeparator: ".",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Antigua and Barbuda",
      currencyCode: "XCD",
      symbol: "$",
      isoCode: "ag",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Argentina",
      currencyCode: "ARS",
      symbol: "$",
      isoCode: "ar",
      thousandSeparator: ".",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Armenia",
      currencyCode: "AMD",
      symbol: "֏",
      isoCode: "am",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Australia",
      currencyCode: "AUD",
      symbol: "$",
      isoCode: "au",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Austria",
      currencyCode: "EUR",
      symbol: "€",
      isoCode: "at",
      thousandSeparator: ".",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Azerbaijan",
      currencyCode: "AZN",
      symbol: "₼",
      isoCode: "az",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Bahamas",
      currencyCode: "BSD",
      symbol: "$",
      isoCode: "bs",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Bahrain",
      currencyCode: "BHD",
      symbol: ".د.ب",
      isoCode: "bh",
      thousandSeparator: ",",
      significantDigits: 3,
      decimalSeparator: ".",
    },
    {
      name: "Bangladesh",
      currencyCode: "BDT",
      symbol: "৳",
      isoCode: "bd",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Barbados",
      currencyCode: "BBD",
      symbol: "$",
      isoCode: "bb",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Belarus",
      currencyCode: "BYN",
      symbol: "Br",
      isoCode: "by",
      thousandSeparator: " ",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Belgium",
      currencyCode: "EUR",
      symbol: "€",
      isoCode: "be",
      thousandSeparator: ".",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Belize",
      currencyCode: "BZD",
      symbol: "$",
      isoCode: "bz",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Benin",
      currencyCode: "XOF",
      symbol: "CFA",
      isoCode: "bj",
      thousandSeparator: " ",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Bhutan",
      currencyCode: "BTN",
      symbol: "Nu.",
      isoCode: "bt",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Bolivia (Plurinational State of)",
      currencyCode: "BOB",
      symbol: "Bs.",
      isoCode: "bo",
      thousandSeparator: ".",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Bosnia and Herzegovina",
      currencyCode: "BAM",
      symbol: "KM",
      isoCode: "ba",
      thousandSeparator: ".",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Botswana",
      currencyCode: "BWP",
      symbol: "P",
      isoCode: "bw",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Brazil",
      currencyCode: "BRL",
      symbol: "R$",
      isoCode: "br",
      thousandSeparator: ".",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Brunei Darussalam",
      currencyCode: "BND",
      symbol: "$",
      isoCode: "bn",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Bulgaria",
      currencyCode: "BGN",
      symbol: "лв",
      isoCode: "bg",
      thousandSeparator: " ",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Burkina Faso",
      currencyCode: "XOF",
      symbol: "CFA",
      isoCode: "bf",
      thousandSeparator: " ",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Burundi",
      currencyCode: "BIF",
      symbol: "FBu",
      isoCode: "bi",
      thousandSeparator: " ",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Cabo Verde",
      currencyCode: "CVE",
      symbol: "$",
      isoCode: "cv",
      thousandSeparator: ".",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Cambodia",
      currencyCode: "KHR",
      symbol: "៛",
      isoCode: "kh",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Cameroon",
      currencyCode: "XAF",
      symbol: "FCFA",
      isoCode: "cm",
      thousandSeparator: " ",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Canada",
      currencyCode: "CAD",
      symbol: "$",
      isoCode: "ca",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Central African Republic",
      currencyCode: "XAF",
      symbol: "FCFA",
      isoCode: "cf",
      thousandSeparator: " ",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Chad",
      currencyCode: "XAF",
      symbol: "FCFA",
      isoCode: "td",
      thousandSeparator: " ",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Chile",
      currencyCode: "CLP",
      symbol: "$",
      isoCode: "cl",
      thousandSeparator: ".",
      significantDigits: 0,
      decimalSeparator: ",",
    },
    {
      name: "China",
      currencyCode: "CNY",
      symbol: "¥",
      isoCode: "cn",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Colombia",
      currencyCode: "COP",
      symbol: "$",
      isoCode: "co",
      thousandSeparator: ".",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Comoros",
      currencyCode: "KMF",
      symbol: "CF",
      isoCode: "km",
      thousandSeparator: " ",
      significantDigits: 0,
      decimalSeparator: ",",
    },
    {
      name: "Congo",
      currencyCode: "XAF",
      symbol: "FCFA",
      isoCode: "cg",
      thousandSeparator: " ",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Costa Rica",
      currencyCode: "CRC",
      symbol: "₡",
      isoCode: "cr",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Côte d'Ivoire",
      currencyCode: "XOF",
      symbol: "CFA",
      isoCode: "ci",
      thousandSeparator: " ",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Croatia",
      currencyCode: "HRK",
      symbol: "kn",
      isoCode: "hr",
      thousandSeparator: ".",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Cuba",
      currencyCode: "CUP",
      symbol: "$",
      isoCode: "cu",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Cyprus",
      currencyCode: "EUR",
      symbol: "€",
      isoCode: "cy",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Czech Republic",
      currencyCode: "CZK",
      symbol: "Kč",
      isoCode: "cz",
      thousandSeparator: " ",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Denmark",
      currencyCode: "DKK",
      symbol: "kr",
      isoCode: "dk",
      thousandSeparator: ".",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Djibouti",
      currencyCode: "DJF",
      symbol: "Fdj",
      isoCode: "dj",
      thousandSeparator: ",",
      significantDigits: 0,
      decimalSeparator: ".",
    },
    {
      name: "Dominica",
      currencyCode: "XCD",
      symbol: "$",
      isoCode: "dm",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Dominican Republic",
      currencyCode: "DOP",
      symbol: "RD$",
      isoCode: "do",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Ecuador",
      currencyCode: "USD",
      symbol: "$",
      isoCode: "ec",
      thousandSeparator: ".",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Egypt",
      currencyCode: "EGP",
      symbol: "ج.م",
      isoCode: "eg",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "El Salvador",
      currencyCode: "USD",
      symbol: "$",
      isoCode: "sv",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Equatorial Guinea",
      currencyCode: "XAF",
      symbol: "FCFA",
      isoCode: "gq",
      thousandSeparator: " ",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Eritrea",
      currencyCode: "ERN",
      symbol: "Nkf",
      isoCode: "er",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Estonia",
      currencyCode: "EUR",
      symbol: "€",
      isoCode: "ee",
      thousandSeparator: " ",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Eswatini",
      currencyCode: "SZL",
      symbol: "E",
      isoCode: "sz",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Ethiopia",
      currencyCode: "ETB",
      symbol: "Br",
      isoCode: "et",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Fiji",
      currencyCode: "FJD",
      symbol: "FJ$",
      isoCode: "fj",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Finland",
      currencyCode: "EUR",
      symbol: "€",
      isoCode: "fi",
      thousandSeparator: " ",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "France",
      currencyCode: "EUR",
      symbol: "€",
      isoCode: "fr",
      thousandSeparator: " ",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Gabon",
      currencyCode: "XAF",
      symbol: "FCFA",
      isoCode: "ga",
      thousandSeparator: " ",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Gambia",
      currencyCode: "GMD",
      symbol: "D",
      isoCode: "gm",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Georgia",
      currencyCode: "GEL",
      symbol: "₾",
      isoCode: "ge",
      thousandSeparator: " ",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Germany",
      currencyCode: "EUR",
      symbol: "€",
      isoCode: "de",
      thousandSeparator: ".",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Ghana",
      currencyCode: "GHS",
      symbol: "GH₵",
      isoCode: "gh",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Greece",
      currencyCode: "EUR",
      symbol: "€",
      isoCode: "gr",
      thousandSeparator: ".",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Grenada",
      currencyCode: "XCD",
      symbol: "$",
      isoCode: "gd",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Guatemala",
      currencyCode: "GTQ",
      symbol: "Q",
      isoCode: "gt",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Guinea",
      currencyCode: "GNF",
      symbol: "FG",
      isoCode: "gn",
      thousandSeparator: " ",
      significantDigits: 0,
      decimalSeparator: ".",
    },
    {
      name: "Guinea-Bissau",
      currencyCode: "XOF",
      symbol: "CFA",
      isoCode: "gw",
      thousandSeparator: ",",
      significantDigits: 0,
      decimalSeparator: ".",
    },
    {
      name: "Guyana",
      currencyCode: "GYD",
      symbol: "$",
      isoCode: "gy",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Haiti",
      currencyCode: "HTG",
      symbol: "G",
      isoCode: "ht",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Honduras",
      currencyCode: "HNL",
      symbol: "L",
      isoCode: "hn",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Hungary",
      currencyCode: "HUF",
      symbol: "Ft",
      isoCode: "hu",
      thousandSeparator: " ",
      significantDigits: 0,
      decimalSeparator: ",",
    },
    {
      name: "Iceland",
      currencyCode: "ISK",
      symbol: "kr",
      isoCode: "is",
      thousandSeparator: ".",
      significantDigits: 0,
      decimalSeparator: ",",
    },
    {
      name: "India",
      currencyCode: "INR",
      symbol: "₹",
      isoCode: "in",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Indonesia",
      currencyCode: "IDR",
      symbol: "Rp",
      isoCode: "id",
      thousandSeparator: ".",
      significantDigits: 0,
      decimalSeparator: ",",
    },
    {
      name: "Iran",
      currencyCode: "IRR",
      symbol: "﷼",
      isoCode: "ir",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Iraq",
      currencyCode: "IQD",
      symbol: "ع.د",
      isoCode: "iq",
      thousandSeparator: ",",
      significantDigits: 3,
      decimalSeparator: ".",
    },
    {
      name: "Ireland",
      currencyCode: "EUR",
      symbol: "€",
      isoCode: "ie",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Israel",
      currencyCode: "ILS",
      symbol: "₪",
      isoCode: "il",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Italy",
      currencyCode: "EUR",
      symbol: "€",
      isoCode: "it",
      thousandSeparator: ".",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Jamaica",
      currencyCode: "JMD",
      symbol: "$",
      isoCode: "jm",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Japan",
      currencyCode: "JPY",
      symbol: "¥",
      isoCode: "jp",
      thousandSeparator: ",",
      significantDigits: 0,
      decimalSeparator: ".",
    },
    {
      name: "Jordan",
      currencyCode: "JOD",
      symbol: "د.ا",
      isoCode: "jo",
      thousandSeparator: ",",
      significantDigits: 3,
      decimalSeparator: ".",
    },
    {
      name: "Kazakhstan",
      currencyCode: "KZT",
      symbol: "₸",
      isoCode: "kz",
      thousandSeparator: " ",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Kenya",
      currencyCode: "KES",
      symbol: "KSh",
      isoCode: "ke",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Kiribati",
      currencyCode: "AUD",
      symbol: "$",
      isoCode: "ki",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Kuwait",
      currencyCode: "KWD",
      symbol: "د.ك",
      isoCode: "kw",
      thousandSeparator: ",",
      significantDigits: 3,
      decimalSeparator: ".",
    },
    {
      name: "Kyrgyzstan",
      currencyCode: "KGS",
      symbol: "сом",
      isoCode: "kg",
      thousandSeparator: " ",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Laos",
      currencyCode: "LAK",
      symbol: "₭",
      isoCode: "la",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Latvia",
      currencyCode: "EUR",
      symbol: "€",
      isoCode: "lv",
      thousandSeparator: " ",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Lebanon",
      currencyCode: "LBP",
      symbol: "ل.ل",
      isoCode: "lb",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Lesotho",
      currencyCode: "LSL",
      symbol: "L",
      isoCode: "ls",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Liberia",
      currencyCode: "LRD",
      symbol: "$",
      isoCode: "lr",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Libya",
      currencyCode: "LYD",
      symbol: "ل.د",
      isoCode: "ly",
      thousandSeparator: ",",
      significantDigits: 3,
      decimalSeparator: ".",
    },
    {
      name: "Liechtenstein",
      currencyCode: "CHF",
      symbol: "Fr.",
      isoCode: "li",
      thousandSeparator: "'",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Lithuania",
      currencyCode: "EUR",
      symbol: "€",
      isoCode: "lt",
      thousandSeparator: " ",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Luxembourg",
      currencyCode: "EUR",
      symbol: "€",
      isoCode: "lu",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Madagascar",
      currencyCode: "MGA",
      symbol: "Ar",
      isoCode: "mg",
      thousandSeparator: " ",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Malawi",
      currencyCode: "MWK",
      symbol: "MK",
      isoCode: "mw",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Malaysia",
      currencyCode: "MYR",
      symbol: "RM",
      isoCode: "my",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Maldives",
      currencyCode: "MVR",
      symbol: "Rf",
      isoCode: "mv",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Mali",
      currencyCode: "XOF",
      symbol: "CFA",
      isoCode: "ml",
      thousandSeparator: " ",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Myanmar",
      currencyCode: "MMK",
      symbol: "K",
      isoCode: "mm",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Nepal",
      currencyCode: "NPR",
      symbol: "₨",
      isoCode: "np",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Netherlands",
      currencyCode: "EUR",
      symbol: "€",
      isoCode: "nl",
      thousandSeparator: ".",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "New Zealand",
      currencyCode: "NZD",
      symbol: "$",
      isoCode: "nz",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Nigeria",
      currencyCode: "NGN",
      symbol: "₦",
      isoCode: "ng",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "North Korea",
      currencyCode: "KPW",
      symbol: "₩",
      isoCode: "kp",
      thousandSeparator: ",",
      significantDigits: 0,
      decimalSeparator: ".",
    },
    {
      name: "Norway",
      currencyCode: "NOK",
      symbol: "kr",
      isoCode: "no",
      thousandSeparator: " ",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Pakistan",
      currencyCode: "PKR",
      symbol: "₨",
      isoCode: "pk",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Palestine",
      currencyCode: "ILS",
      symbol: "₪",
      isoCode: "ps",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Peru",
      currencyCode: "PEN",
      symbol: "S/.",
      isoCode: "pe",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Philippines",
      currencyCode: "PHP",
      symbol: "₱",
      isoCode: "ph",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Poland",
      currencyCode: "PLN",
      symbol: "zł",
      isoCode: "pl",
      thousandSeparator: " ",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Portugal",
      currencyCode: "EUR",
      symbol: "€",
      isoCode: "pt",
      thousandSeparator: ".",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Romania",
      currencyCode: "RON",
      symbol: "lei",
      isoCode: "ro",
      thousandSeparator: ".",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Russia",
      currencyCode: "RUB",
      symbol: "₽",
      isoCode: "ru",
      thousandSeparator: ".",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Saudi Arabia",
      currencyCode: "SAR",
      symbol: "ر.س",
      isoCode: "sa",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Serbia",
      currencyCode: "RSD",
      symbol: "дин.",
      isoCode: "rs",
      thousandSeparator: ".",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Seychelles",
      currencyCode: "SCR",
      symbol: "SCR",
      isoCode: "sc",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Sierra Leone",
      currencyCode: "SLL",
      symbol: "Le",
      isoCode: "sl",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Singapore",
      currencyCode: "SGD",
      symbol: "$",
      isoCode: "sg",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Sint Maarten",
      currencyCode: "ANG",
      symbol: "ƒ",
      isoCode: "sx",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Slovakia",
      currencyCode: "EUR",
      symbol: "€",
      isoCode: "sk",
      thousandSeparator: " ",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Slovenia",
      currencyCode: "EUR",
      symbol: "€",
      isoCode: "si",
      thousandSeparator: ".",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Solomon Islands",
      currencyCode: "SBD",
      symbol: "SI$",
      isoCode: "sb",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Somalia",
      currencyCode: "SOS",
      symbol: "SOS",
      isoCode: "so",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "South Africa",
      currencyCode: "ZAR",
      symbol: "R",
      isoCode: "za",
      thousandSeparator: " ",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "South Korea",
      currencyCode: "KRW",
      symbol: "₩",
      isoCode: "kr",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Spain",
      currencyCode: "EUR",
      symbol: "€",
      isoCode: "es",
      thousandSeparator: ".",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Sri Lanka",
      currencyCode: "LKR",
      symbol: "Rs",
      isoCode: "lk",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Sudan",
      currencyCode: "SDG",
      symbol: "SDG",
      isoCode: "sd",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Suriname",
      currencyCode: "SRD",
      symbol: "$",
      isoCode: "sr",
      thousandSeparator: ".",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Swaziland",
      currencyCode: "SZL",
      symbol: "E",
      isoCode: "sz",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Sweden",
      currencyCode: "SEK",
      symbol: "kr",
      isoCode: "se",
      thousandSeparator: " ",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Switzerland",
      currencyCode: "CHF",
      symbol: "CHF",
      isoCode: "ch",
      thousandSeparator: "'",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Syria",
      currencyCode: "SYP",
      symbol: "£",
      isoCode: "sy",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Taiwan",
      currencyCode: "TWD",
      symbol: "NT$",
      isoCode: "tw",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Tajikistan",
      currencyCode: "TJS",
      symbol: "TJS",
      isoCode: "tj",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Tanzania",
      currencyCode: "TZS",
      symbol: "TZS",
      isoCode: "tz",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Thailand",
      currencyCode: "THB",
      symbol: "฿",
      isoCode: "th",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Timor-Leste",
      currencyCode: "USD",
      symbol: "$",
      isoCode: "tl",
      thousandSeparator: ".",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Togo",
      currencyCode: "XOF",
      symbol: "CFA",
      isoCode: "tg",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Tonga",
      currencyCode: "TOP",
      symbol: "T$",
      isoCode: "to",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Trinidad and Tobago",
      currencyCode: "TTD",
      symbol: "$",
      isoCode: "tt",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Tunisia",
      currencyCode: "TND",
      symbol: "د.ت",
      isoCode: "tn",
      thousandSeparator: ",",
      significantDigits: 3,
      decimalSeparator: ".",
    },
    {
      name: "Turkey",
      currencyCode: "TRY",
      symbol: "₺",
      isoCode: "tr",
      thousandSeparator: ".",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Turkmenistan",
      currencyCode: "TMT",
      symbol: "T",
      isoCode: "tm",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Tuvalu",
      currencyCode: "AUD",
      symbol: "$",
      isoCode: "tv",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Uganda",
      currencyCode: "UGX",
      symbol: "USh",
      isoCode: "ug",
      thousandSeparator: ",",
      significantDigits: 0,
      decimalSeparator: ".",
    },
    {
      name: "Ukraine",
      currencyCode: "UAH",
      symbol: "₴",
      isoCode: "ua",
      thousandSeparator: " ",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "United Arab Emirates",
      currencyCode: "AED",
      symbol: "د.إ",
      isoCode: "ae",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "United Kingdom",
      currencyCode: "GBP",
      symbol: "£",
      isoCode: "gb",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "United States of America",
      currencyCode: "USD",
      symbol: "$",
      isoCode: "us",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Uruguay",
      currencyCode: "UYU",
      symbol: "$U",
      isoCode: "uy",
      thousandSeparator: ".",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Uzbekistan",
      currencyCode: "UZS",
      symbol: "so'm",
      isoCode: "uz",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Vanuatu",
      currencyCode: "VUV",
      symbol: "VT",
      isoCode: "vu",
      thousandSeparator: ",",
      significantDigits: 0,
      decimalSeparator: ".",
    },
    {
      name: "Venezuela",
      currencyCode: "VEF",
      symbol: "Bs.",
      isoCode: "ve",
      thousandSeparator: ".",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Vietnam",
      currencyCode: "VND",
      symbol: "₫",
      isoCode: "vn",
      thousandSeparator: ".",
      significantDigits: 2,
      decimalSeparator: ",",
    },
    {
      name: "Yemen",
      currencyCode: "YER",
      symbol: "﷼",
      isoCode: "ye",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Zambia",
      currencyCode: "ZMW",
      symbol: "ZK",
      isoCode: "zm",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
    {
      name: "Zimbabwe",
      currencyCode: "ZWL",
      symbol: "Z$",
      isoCode: "zw",
      thousandSeparator: ",",
      significantDigits: 2,
      decimalSeparator: ".",
    },
  ],
};

export default CURRENCY_CONSTANTS;
