const MODAL_TYPE_CONSTANTS = {
  DATE_PICKER: "DATE_PICKER",
  DATE_AND_TIME_PICKER: "DATE_AND_TIME_PICKER",
  LIST: "LIST",
  CURRENCY_LIST: "CURRENCY_LIST",
  TEXT_INPUT: "TEXT_INPUT",
  COLOR_PICKER: "COLOR_PICKER",
  ICON_PICKER: "ICON_PICKER",
  ACTION: "ACTION",
  NUMBER_PICKER: "NUMBER_PICKER",
};
export default MODAL_TYPE_CONSTANTS;
