const SECRET_KEYS = {
  FEATURE_SWITCH_COLLECTION_NAME: "FEATURE_SWITCH_COLLECTION_NAME",
  FEATURE_SWITCH_DOCUMENT_ID: "FEATURE_SWITCH_DOCUMENT_ID",
  FEATURE_COLLECTION_NAME: "FEATURE_COLLECTION_NAME",
  FEATURE_DOCUMENT_ID: "FEATURE_DOCUMENT_ID",
  RAPID_API_KEY: "RAPID_API_KEY",
  REVENUE_CAT_GOOGLE_API_KEY: "REVENUE_CAT_GOOGLE_API_KEY",
};

export default SECRET_KEYS;
