import {
  PROD_FIREBASE_API_KEY,
  PROD_FIREBASE_PROJECT_ID,
  PROD_FIREBASE_AUTH_DOMAIN,
  PROD_FIREBASE_STORAGE_BUCKET,
  PROD_FIREBASE_MESSAGING_SENDER_ID,
  PROD_FIREBASE_APP_ID,
  PROD_FIREBASE_MEASUREMENT_ID,
  LOGSNAG_API_KEY,
  LOGSNAG_API_URL,
  SENTRY_DSN,
  SENTRY_AUTH_TOKEN,
  REVENUE_CAT_GOOGLE_API_KEY,
  RAPID_API_KEY,
  RAPID_API_HOST,
  RAPID_API_URL,
  FEATURE_COLLECTION_NAME,
  FEATURE_DOCUMENT_ID,
} from "@env";

const prodEnv = {
  FIREBASE_CONFIG: {
    API_KEY: PROD_FIREBASE_API_KEY,
    AUTH_DOMAIN: PROD_FIREBASE_AUTH_DOMAIN,
    PROJECT_ID: PROD_FIREBASE_PROJECT_ID,
    STORAGE_BUCKET: PROD_FIREBASE_STORAGE_BUCKET,
    MESSAGING_SENDER_ID: PROD_FIREBASE_MESSAGING_SENDER_ID,
    APP_ID: PROD_FIREBASE_APP_ID,
    MEASUREMENT_ID: PROD_FIREBASE_MEASUREMENT_ID,
  },
  SENTRY_CONFIG: {
    SENTRY_DSN: SENTRY_DSN,
    AUTH_TOKEN: SENTRY_AUTH_TOKEN,
  },
  logSnagConfig: {
    apiKey: LOGSNAG_API_KEY,
    apiUrl: LOGSNAG_API_URL,
  },
  REVENUE_CAT: {
    GOOGLE_API_KEY: REVENUE_CAT_GOOGLE_API_KEY,
  },
  RAPID_API: {
    API_KEY: RAPID_API_KEY,
    HOST: RAPID_API_HOST,
    URL: RAPID_API_URL,
  },
  SUBSCRIPTION: {
    FEATURE_COLLECTION_NAME: FEATURE_COLLECTION_NAME,
    FEATURE_DOCUMENT_ID: FEATURE_DOCUMENT_ID,
  },
};

export default __DEV__ ? prodEnv : prodEnv;
