const categoriesFallback = ({
  uid = null,
  created_at = null,
  updated_at = null,
}) => {
  return {
    uid: uid,
    expense: [
      {
        name: "initial balance",
        id: "initial_balance_expense",
        icon: { name: "duplicate", color: "default", pack: "IonIcons" },
        is_deletable: false,
        is_shown: true,
        _timestamps: {
          created_at: Date.now() || created_at,
          created_by: null || uid,
          updated_at: Date.now() || updated_at,
          updated_by: null || uid,
        },
      },
      {
        name: "debt payment",
        id: "debt_payment",
        icon: {
          name: "cash",
          color: "default",
          pack: "IonIcons",
        },
        is_deletable: false,
        is_shown: true,
        _timestamps: {
          created_at: Date.now() || created_at,
          created_by: null || uid,
          updated_at: Date.now() || updated_at,
          updated_by: null || uid,
        },
      },
      {
        name: "loan",
        id: "loan",
        icon: {
          name: "cash",
          color: "default",
          pack: "IonIcons",
        },
        is_deletable: false,
        is_shown: true,
        _timestamps: {
          created_at: Date.now() || created_at,
          created_by: null || uid,
          updated_at: Date.now() || updated_at,
          updated_by: null || uid,
        },
      },
      {
        name: "food and drink",
        id: "1",
        icon: { name: "fast-food", color: "default", pack: "IonIcons" },
        is_deletable: true,
        is_shown: true,
        _timestamps: {
          created_at: Date.now() || created_at,
          created_by: null || uid,
          updated_at: Date.now() || updated_at,
          updated_by: null || uid,
        },
      },
      {
        name: "bills and utilities",
        id: "2",
        icon: { name: "flash", color: "default", pack: "IonIcons" },
        is_deletable: true,
        is_shown: true,
        _timestamps: {
          created_at: Date.now() || created_at,
          created_by: null || uid,
          updated_at: Date.now() || updated_at,
          updated_by: null || uid,
        },
      },
      {
        name: "transportation",
        id: "3",
        icon: { name: "bus", color: "default", pack: "IonIcons" },
        is_deletable: true,
        is_shown: true,
        _timestamps: {
          created_at: Date.now() || created_at,
          created_by: null || uid,
          updated_at: Date.now() || updated_at,
          updated_by: null || uid,
        },
      },
      {
        name: "shopping",
        id: "4",
        icon: { name: "cart", color: "default", pack: "IonIcons" },
        is_deletable: true,
        is_shown: true,
        _timestamps: {
          created_at: Date.now() || created_at,
          created_by: null || uid,
          updated_at: Date.now() || updated_at,
          updated_by: null || uid,
        },
      },
      {
        name: "entertainment",
        id: "5",
        icon: { name: "game-controller", color: "default", pack: "IonIcons" },
        is_deletable: true,
        is_shown: true,
        _timestamps: {
          created_at: Date.now() || created_at,
          created_by: null || uid,
          updated_at: Date.now() || updated_at,
          updated_by: null || uid,
        },
      },
      {
        name: "travel",
        id: "6",
        icon: { name: "airplane", color: "default", pack: "IonIcons" },
        is_deletable: true,
        is_shown: true,
        _timestamps: {
          created_at: Date.now() || created_at,
          created_by: null || uid,
          updated_at: Date.now() || updated_at,
          updated_by: null || uid,
        },
      },
      {
        name: "health",
        id: "7",
        icon: { name: "medical", color: "default", pack: "IonIcons" },
        is_deletable: true,
        is_shown: true,
        _timestamps: {
          created_at: Date.now() || created_at,
          created_by: null || uid,
          updated_at: Date.now() || updated_at,
          updated_by: null || uid,
        },
      },
      {
        name: "sport",
        id: "8",
        icon: { name: "football", color: "default", pack: "IonIcons" },
        is_deletable: true,
        is_shown: true,
        _timestamps: {
          created_at: Date.now() || created_at,
          created_by: null || uid,
          updated_at: Date.now() || updated_at,
          updated_by: null || uid,
        },
      },
      {
        name: "donations",
        id: "9",
        icon: { name: "heart", color: "default", pack: "IonIcons" },
        is_deletable: true,
        is_shown: true,
        _timestamps: {
          created_at: Date.now() || created_at,
          created_by: null || uid,
          updated_at: Date.now() || updated_at,
          updated_by: null || uid,
        },
      },
      {
        name: "education",
        id: "10",
        icon: { name: "school", color: "default", pack: "IonIcons" },
        is_deletable: true,
        is_shown: true,
        _timestamps: {
          created_at: Date.now() || created_at,
          created_by: null || uid,
          updated_at: Date.now() || updated_at,
          updated_by: null || uid,
        },
      },
      {
        name: "subscription",
        id: "11",
        icon: { name: "receipt", color: "default", pack: "IonIcons" },
        is_deletable: true,
        is_shown: true,
        _timestamps: {
          created_at: Date.now() || created_at,
          created_by: null || uid,
          updated_at: Date.now() || updated_at,
          updated_by: null || uid,
        },
      },
      {
        name: "gadget",
        id: "12",
        icon: { name: "phone-portrait", color: "default", pack: "IonIcons" },
        is_deletable: true,
        is_shown: true,
        _timestamps: {
          created_at: Date.now() || created_at,
          created_by: null || uid,
          updated_at: Date.now() || updated_at,
          updated_by: null || uid,
        },
      },
    ],
    income: [
      {
        name: "debt",
        id: "debt",
        icon: {
          name: "add-circle-outline",
          color: "default",
          pack: "IonIcons",
        },
        is_deletable: false,
        is_shown: true,
        _timestamps: {
          created_at: Date.now() || created_at,
          created_by: null || uid,
          updated_at: Date.now() || updated_at,
          updated_by: null || uid,
        },
      },
      {
        name: "loan collection",
        id: "loan_collection",
        icon: {
          name: "add-circle-outline",
          color: "default",
          pack: "IonIcons",
        },
        is_deletable: false,
        is_shown: true,
        _timestamps: {
          created_at: Date.now() || created_at,
          created_by: null || uid,
          updated_at: Date.now() || updated_at,
          updated_by: null || uid,
        },
      },
      {
        name: "salary",
        id: "13",
        icon: { name: "cash", color: "default", pack: "IonIcons" },
        is_deletable: true,
        is_shown: true,
        _timestamps: {
          created_at: Date.now() || created_at,
          created_by: null || uid,
          updated_at: Date.now() || updated_at,
          updated_by: null || uid,
        },
      },
      {
        name: "bonus",
        id: "14",
        icon: { name: "gift", color: "default", pack: "IonIcons" },
        is_deletable: true,
        is_shown: true,
        _timestamps: {
          created_at: Date.now() || created_at,
          created_by: null || uid,
          updated_at: Date.now() || updated_at,
          updated_by: null || uid,
        },
      },
      {
        name: "interest",
        id: "15",
        icon: { name: "trending-up", color: "default", pack: "IonIcons" },
        is_deletable: true,
        is_shown: true,
        _timestamps: {
          created_at: Date.now() || created_at,
          created_by: null || uid,
          updated_at: Date.now() || updated_at,
          updated_by: null || uid,
        },
      },
      {
        name: "selling",
        id: "16",
        icon: { name: "basket", color: "default", pack: "IonIcons" },
        is_deletable: true,
        is_shown: true,
        _timestamps: {
          created_at: Date.now() || created_at,
          created_by: null || uid,
          updated_at: Date.now() || updated_at,
          updated_by: null || uid,
        },
      },
      {
        name: "initial balance",
        id: "initial_balance_income",
        icon: { name: "duplicate", color: "default", pack: "IonIcons" },
        is_deletable: false,
        is_shown: true,
        _timestamps: {
          created_at: Date.now() || created_at,
          created_by: null || uid,
          updated_at: Date.now() || updated_at,
          updated_by: null || uid,
        },
      },
    ],
  };
};
export default categoriesFallback;
